// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4198.RoboCats;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CANTalon;
import edu.wpi.first.wpilibj.RobotDrive;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static CANTalon driveBaseSublf;
    public static CANTalon driveBaseSubrf;
    public static CANTalon driveBaseSublr;
    public static CANTalon driveBaseSubrr;
    public static RobotDrive driveBaseSubrobotDrive;
    public static CANTalon shooterSubsystemshooterTalon1;
    public static CANTalon shooterSubsystemshooterTalon2;
    public static CANTalon shooterSubsystemshooterTalon3;
    public static CANTalon shooterSubsystemshooterTalon4;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveBaseSublf = new CANTalon(0);
        LiveWindow.addActuator("DriveBaseSub", "lf", driveBaseSublf);
        
        driveBaseSubrf = new CANTalon(1);
        LiveWindow.addActuator("DriveBaseSub", "rf", driveBaseSubrf);
        
        driveBaseSublr = new CANTalon(2);
        LiveWindow.addActuator("DriveBaseSub", "lr", driveBaseSublr);
        
        driveBaseSubrr = new CANTalon(3);
        LiveWindow.addActuator("DriveBaseSub", "rr", driveBaseSubrr);
        
        driveBaseSubrobotDrive = new RobotDrive(driveBaseSublf, driveBaseSublr,
              driveBaseSubrf, driveBaseSubrr);
        
        driveBaseSubrobotDrive.setSafetyEnabled(false);
        driveBaseSubrobotDrive.setExpiration(0.0);
        driveBaseSubrobotDrive.setSensitivity(0.5);
        driveBaseSubrobotDrive.setMaxOutput(1.0);
        driveBaseSubrobotDrive.setInvertedMotor(RobotDrive.MotorType.kFrontLeft, true);
        driveBaseSubrobotDrive.setInvertedMotor(RobotDrive.MotorType.kRearLeft, true);
        shooterSubsystemshooterTalon1 = new CANTalon(4);
        LiveWindow.addActuator("ShooterSubsystem", "shooterTalon1", shooterSubsystemshooterTalon1);
        
        shooterSubsystemshooterTalon2 = new CANTalon(5);
        LiveWindow.addActuator("ShooterSubsystem", "shooterTalon2", shooterSubsystemshooterTalon2);
        
        shooterSubsystemshooterTalon3 = new CANTalon(6);
        LiveWindow.addActuator("ShooterSubsystem", "shooterTalon3", shooterSubsystemshooterTalon3);
        
        shooterSubsystemshooterTalon4 = new CANTalon(7);
        LiveWindow.addActuator("ShooterSubsystem", "shooterTalon4", shooterSubsystemshooterTalon4);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
